### ISSUE TITLE
train_astlingen_linux.py

### ISSUE THREAD

**Issue by shentaodeepwave** [zhiyu-zhang-tongji/MARL-UDS#1]
When I run it in a linux environment that is properly configured according to requirements.txt up to around line 156, the following error occurs

        Due to architectural limitations inside of EPA-SWMM
        multiple Simulations cannot be completed within a single
        instance of Python.  Consider launching the model runs
        using a Python Subprocess and a Queue manager.

I know that this is a common problem in swmm programs, but it seems that your code does not solve this problem, running train_astlingen.py,train_chaohu.py both have the same problem!
In addition, running plot_train.py results in a file path error!

Reading your paper is very inspiring, I hope to get the problem solved!

**Comment by Zhiyu014** [comment]
Hi @shentaodeepwave ! Thanks for your interest in this work.
The multi-simulation problem occurs in the new pyswmm version (>=2.0.0). As I'm not updating this repo recently, you can try installing pyswmm<=1.5.1 or older.

**Comment by shentaodeepwave** [comment]
> 嗨 ！感谢您对这项工作的关注。多重模拟问题出现在新的 pyswmm 版本 （>=2.0.0） 中。由于我最近没有更新此存储库，因此您可以尝试安装 pyswmm<=1.5.1 或更早版本。

Thank you for your immediate reply, your program is working correctly on my computer!
