### ISSUE TITLE
getGagePrecip() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by shentaodeepwave** [zhiyu-zhang-tongji/MARL-UDS#2]
When I run train_astlingen_linux.py the following problem occurs, I have tried to run the following two sentences under the file environment_astlingen.py, 

    print("ID: ", ID)
    print("tkai.RainGageResults.rainfall.value: ", tkai.RainGageResults.rainfall.value)
I get this output.

    ID:  RG1
    tkai.RainGageResults.rainfall.value:  1
I was not able to modify this part of the program by myself, so I wrote this issue to ask for help.
The full error message is as follows

     o  Retrieving project data o  Retrieving project data
    
     o  Retrieving project data
     o  Retrieving project data o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
    
     o  Retrieving project data o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
    
     o  Retrieving project data o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
    
    
     o  Retrieving project data o  Retrieving project data
     o  Retrieving project data o  Retrieving project data
     o  Retrieving project data
    
     o  Retrieving project data o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
    
     o  Retrieving project data o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
    
    
     o  Retrieving project data o  Retrieving project data o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
    
     o  Retrieving project data o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project data
     o  Retrieving project datamultiprocessing.pool.RemoteTraceback: 
    """
    Traceback (most recent call last):
      File "/home/xtwang/miniconda3/envs/storm/lib/python3.8/multiprocessing/pool.py", line 125, in worker
        result = (True, func(*args, **kwds))
      File "/home/xtwang/MARL-UDS-main/storm/train_astlingen_linux.py", line 59, in bc_test
        _ = env.reset(event)
      File "/home/xtwang/MARL-UDS-main/storm/envs/astlingen.py", line 207, in reset
        state = self.state(seq)
      File "/home/xtwang/MARL-UDS-main/storm/envs/astlingen.py", line 138, in state
        __state = self.env._state()
      File "/home/xtwang/miniconda3/envs/storm/lib/python3.8/site-packages/pystorms/environment.py", line 92, in _state
        state.append(self.methods[attribute](ID))
      File "/home/xtwang/MARL-UDS-main/storm/envs/environment_astlingen.py", line 44, in _getGageRainfall
        return self.sim._model.getGagePrecip(ID,
    TypeError: getGagePrecip() takes 2 positional arguments but 3 were given
    """
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/xtwang/MARL-UDS-main/storm/train_astlingen_linux.py", line 157, in <module>
        bc_trains = [r.get() for r in res[:len(train_events)]]
      File "/home/xtwang/MARL-UDS-main/storm/train_astlingen_linux.py", line 157, in <listcomp>
        bc_trains = [r.get() for r in res[:len(train_events)]]
      File "/home/xtwang/miniconda3/envs/storm/lib/python3.8/multiprocessing/pool.py", line 771, in get
        raise self._value
    TypeError: getGagePrecip() takes 2 positional arguments but 3 were given

**Comment by Zhiyu014** [comment]
It seems like from the pyswmm class. Could you please provide the pyswmm version?

**Comment by shentaodeepwave** [comment]
Running pip list in the environment gives us 0.5.0.

    $ pip list
    Package                 Version
    ----------------------- -----------
    about-time              4.2.1
    absl-py                 2.1.0
    aenum                   3.1.11
    alive-progress          3.1.5
    astunparse              1.6.3
    autograd                1.7.0
    cachetools              5.5.0
    certifi                 2024.8.30
    charset-normalizer      3.4.0
    cloudpickle             3.1.0
    cma                     3.2.2
    contourpy               1.1.1
    cycler                  0.12.1
    decorator               5.1.1
    Deprecated              1.2.15
    dill                    0.3.9
    dm-tree                 0.1.8
    fonttools               4.55.0
    gast                    0.3.3
    google-auth             2.36.0
    google-auth-oauthlib    1.0.0
    google-pasta            0.2.0
    grapheme                0.6.0
    grpcio                  1.68.0
    h5py                    2.10.0
    idna                    3.10
    importlib_metadata      8.5.0
    importlib_resources     6.4.5
    joblib                  1.4.2
    julian                  0.14
    keras                   2.15.0
    Keras-Preprocessing     1.1.2
    kiwisolver              1.4.7
    lxml                    5.3.0
    Markdown                3.7
    MarkupSafe              2.1.5
    matplotlib              3.5.2
    networkx                3.1
    numpy                   1.18.5
    oauthlib                3.2.2
    opt_einsum              3.4.0
    packaging               24.2
    pandas                  1.4.4
    pillow                  10.4.0
    pip                     24.2
    protobuf                3.19.6
    pyasn1                  0.6.1
    pyasn1_modules          0.4.1
    pymoo                   0.6.0
    pyparsing               3.1.4
    pystorms                1.0.0
    pyswmm                  0.5.0
    python-dateutil         2.9.0.post0
    pytz                    2024.2
    PyYAML                  6.0.2
    requests                2.32.3
    requests-oauthlib       2.0.0
    rsa                     4.9
    scikit-learn            1.2.2
    scipy                   1.4.1
    setuptools              75.1.0
    six                     1.16.0
    spektral                1.2.0
    swmm-api                0.2.0.18.3
    swmm-toolkit            0.15.5
    tensorboard             2.14.0
    tensorboard-data-server 0.7.2
    tensorflow              2.3.0
    tensorflow-estimator    2.3.0
    tensorflow-probability  0.11.1
    termcolor               2.4.0
    threadpoolctl           3.5.0
    tqdm                    4.67.1
    urllib3                 2.2.3
    Werkzeug                3.0.6
    wheel                   0.44.0
    wrapt                   1.17.0
    zipp                    3.20.2

**Comment by Zhiyu014** [comment]
You can try upgrading your pyswmm to 1.5.1. `pip install pyswmm==1.5.1`
